# deploy/kubernetes/tito-pizzeria/charts/ms-gateway/values.yaml
app:
  image:
    repository: "jose196/tito-gateway"
    tag: "v1.2" 
    pullPolicy: "Always"
  containerPort: 3000
  env:
    NATS_SERVERS: "nats://nats:4222"
    PORT: "3000"
    REPO_GIT: "https://github.com/Rodriguez-22/backend-mc-pnpm.git"

service:
  type: NodePort
  port: 3000
  nodePort: 30080

ingress:
  enabled: true
  className: nginx
  # NUEVO HOST: Usando la nueva IP del VPS
  host: "api.194.163.158.235.nip.io"
  path: /
  pathType: ImplementationSpecific