controller:
  componentName: "jenkins-controller"
  image:
    tag: "2.541.1"
  
  imagePullPolicy: "Always"
  runAsUser: 1000
  fsGroup: 1000
  
  # 👇 NUEVA ESTRUCTURA DEL ADMINISTRADOR 👇
  admin:
    username: "admin"
    password: "admin"

  serviceType: "ClusterIP"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostName: "jenkins.194.163.158.235.nip.io"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - github
    - credentials-binding
    - configuration-as-code
    - dark-theme

  sidecars:
    configAutoReload:
      enabled: false

persistence:
  enabled: true
  existingClaim: "jenkins-pvc"
  storageClass: "microk8s-hostpath"

serviceAccount:
  create: true
  name: "jenkins"

  agent:
  resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "1Gi"
    cpu: "512m"